wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1667954306.395726
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.6
      5: 0.13.5
      8:
      - 4
      - 5
env_name:
  desc: null
  value: StockTradingEnv
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 200000
