wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 4.65e-06]\n  [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n\
    \   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 4.65e-06]\n  [0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n\
    \   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]\n  [0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]\n\
    \  [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00 0.00e+00\n   0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00\
    \ 0.00e+00 0.00e+00]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x15b0914b0>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 200000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1667953364.907023
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 35
      4: 3.10.6
      5: 0.13.5
      8:
      - 4
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([0. 0.], [3. 1.], (2,), float16)
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=210, out_features=400,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=400, out_features=300,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=300, out_features=2,\
    \ bias=True)\n    (5): Tanh()\n  )\n)"
actor_batch_norm_stats:
  desc: null
  value: '[]'
actor_batch_norm_stats_target:
  desc: null
  value: '[]'
actor_target:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=210, out_features=400,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=400, out_features=300,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=300, out_features=2,\
    \ bias=True)\n    (5): Tanh()\n  )\n)"
algo:
  desc: null
  value: DDPG
batch_size:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=212,\
    \ out_features=400, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=400,\
    \ out_features=300, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=300,\
    \ out_features=1, bias=True)\n  )\n)"
critic_batch_norm_stats:
  desc: null
  value: '[]'
critic_batch_norm_stats_target:
  desc: null
  value: '[]'
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=212,\
    \ out_features=400, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=400,\
    \ out_features=300, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=300,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cpu
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x15b2dc100>
env_name:
  desc: null
  value: StockTradingEnv
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: -1
learning_rate:
  desc: null
  value: 0.001
learning_starts:
  desc: null
  value: 100
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x15b08fb50>
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\
    \ 0. 0.\n  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n [0. 0. 0.\
    \ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  0. 0. 0. 0.\
    \ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\
    \ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\
    \ 0. 0. 0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\
    \ 0. 0. 0. 0. 0. 0. 0.\n  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n\
    \ [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n \
    \ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], [[1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n  1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]\n [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1.]\n [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1.\n  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]\n [1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n  1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]\n [1. 1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.\n  1. 1. 1. 1. 1. 1. 1. 1. 1.\
    \ 1. 1. 1. 1. 1. 1. 1. 1. 1.]], (5, 42), float16)"
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "TD3Policy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (mu): Sequential(\n\
    \      (0): Linear(in_features=210, out_features=400, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=400, out_features=300, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=300, out_features=2, bias=True)\n      (5): Tanh()\n\
    \    )\n  )\n  (actor_target): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (mu): Sequential(\n\
    \      (0): Linear(in_features=210, out_features=400, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=400, out_features=300, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=300, out_features=2, bias=True)\n      (5): Tanh()\n\
    \    )\n  )\n  (critic): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n\
    \      (0): Linear(in_features=212, out_features=400, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=400, out_features=300, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=300, out_features=1, bias=True)\n    )\n  )\n \
    \ (critic_target): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n\
    \      (0): Linear(in_features=212, out_features=400, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=400, out_features=300, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=300, out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.td3.policies.TD3Policy'>
policy_delay:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''n_critics'': 1}'
policy_type:
  desc: null
  value: MlpPolicy
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x16a8db1f0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1667953367233812000
target_noise_clip:
  desc: null
  value: 0.0
target_policy_noise:
  desc: null
  value: 0.1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: None
total_timesteps:
  desc: null
  value: 200000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.EPISODE: ''episode''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
